/**
 * Input schemas for the expense ledger.
 * =============================================================================
 * These schemas are the boundary between what a browser sent and what the rest
 * of the code is allowed to assume. Everything past this point works with typed,
 * range-checked values.
 *
 * Two decisions worth stating, because they are easy to get wrong:
 *
 * The amount arrives as a STRING and stays one until `parseAmount` converts it.
 * Letting Zod coerce it to a number would hand the parsing job to
 * `Number("12,50")`, which yields NaN, and to `Number("1.005")`, which yields a
 * value that cannot be represented exactly. The money module already knows how
 * humans type amounts — currency symbols, thousands separators, a comma used as
 * a decimal point — so the schema's job is only to check the field is present.
 *
 * The participant list arrives as JSON in a single form field. A split editor
 * produces a variable-length list of pairs, and FormData's repeated-key encoding
 * would force the server to reassemble that ordering by hand. One JSON field,
 * validated by a real schema, is both simpler and stricter.
 */

import { z } from "zod";

import { MAX_AMOUNT_MINOR } from "@/lib/domain/money";
import { uuidSchema } from "@/lib/validation/households";

export const splitMethodSchema = z.enum(["equal", "exact", "percentage", "shares"]);

/**
 * A single participant's typed value. Left optional because an equal split has
 * nothing to type, and the meaning of the number depends on the method — see
 * `ParticipantInput` in lib/domain/splits.ts.
 */
const participantSchema = z.object({
  userId: uuidSchema,
  input: z.number().finite().nonnegative().optional(),
});

/**
 * Parsed from the JSON field the split editor writes.
 *
 * The upper bound is not arbitrary: it matches the largest household the
 * invitation flow permits, so a request cannot arrive carrying more
 * participants than could possibly be members.
 */
const participantsSchema = z
  .string()
  .transform((raw, ctx) => {
    try {
      return JSON.parse(raw) as unknown;
    } catch {
      ctx.addIssue({ code: "custom", message: "Could not read the split" });
      return z.NEVER;
    }
  })
  .pipe(z.array(participantSchema).min(1, "Select at least one person").max(20));

/** An amount as typed. Converted to minor units by `parseAmount`, not here. */
const amountSchema = z
  .string()
  .trim()
  .min(1, "Enter an amount")
  .max(20, "That amount is too large");

const descriptionSchema = z
  .string()
  .trim()
  .min(1, "Give this expense a description")
  .max(120, "Keep the description under 120 characters");

/**
 * A calendar date, not a timestamp. An expense belongs to the day it was
 * incurred, and attaching a time would make the same purchase sort differently
 * depending on the recorder's timezone.
 */
const spentAtSchema = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, "Choose a valid date")
  .refine((value) => !Number.isNaN(Date.parse(value)), "Choose a valid date");

const noteSchema = z
  .string()
  .trim()
  .max(500, "Keep the note under 500 characters")
  .optional()
  .transform((value) => value || undefined);

/**
 * `categoryId` is genuinely optional — "Uncategorised" is a legitimate answer,
 * and forcing a choice at capture time is exactly the friction that stops people
 * recording expenses at all.
 */
const categorySchema = z
  .union([uuidSchema, z.literal("")])
  .optional()
  .transform((value) => value || null);

export const createExpenseSchema = z.object({
  householdId: uuidSchema,
  description: descriptionSchema,
  amount: amountSchema,
  payerId: uuidSchema,
  categoryId: categorySchema,
  spentAt: spentAtSchema,
  splitMethod: splitMethodSchema,
  participants: participantsSchema,
  note: noteSchema,
  /**
   * Generated by the browser when the form is first rendered, so a retry after a
   * dropped connection — or a double-submitted form — resolves to the expense
   * that already exists instead of creating a second one.
   */
  idempotencyKey: z.string().min(8).max(64).optional(),
});

export const updateExpenseSchema = createExpenseSchema
  .omit({
    idempotencyKey: true,
  })
  .extend({
    expenseId: uuidSchema,
    /**
     * Optimistic concurrency. The client sends back the `updated_at` it rendered;
     * if the row has moved on since, the write is refused rather than silently
     * overwriting a roommate's edit.
     */
    expectedUpdatedAt: z.string().min(1),
  });

export const deleteExpenseSchema = z.object({
  householdId: uuidSchema,
  expenseId: uuidSchema,
});

export const settleUpSchema = z.object({
  householdId: uuidSchema,
  fromUserId: uuidSchema,
  toUserId: uuidSchema,
  amount: amountSchema,
  method: z.enum(["bit", "bank_transfer", "cash", "paypal", "other"]),
  note: noteSchema,
});

export const voidSettlementSchema = z.object({
  householdId: uuidSchema,
  settlementId: uuidSchema,
});

/** Guards against an amount that is valid on its own but absurd as money. */
export const MAX_AMOUNT = MAX_AMOUNT_MINOR;

export type CreateExpenseInput = z.infer<typeof createExpenseSchema>;
export type UpdateExpenseInput = z.infer<typeof updateExpenseSchema>;
export type SettleUpInput = z.infer<typeof settleUpSchema>;
